In [89]:
import cv2 as cv
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier

In [90]:
images = [];

In [91]:
train = pd.read_csv("train.csv");
df = train;
df_thresholded = train;
display(df);

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [92]:

itt = 0;

def make_img(row):
    global itt;
    
    img = np.random.randint(222, size=(28, 28))
    #print(img);

    print(itt);
    itt += 1;

    col = "pixel";

    for i in range(784):
        img[i // 28][i % 28] = row[col + str(i)];
    
    gen = np.array(img ,dtype=np.uint8)
    ret,thresh1 = cv.threshold(gen,127,255,cv.THRESH_BINARY);
    gen = thresh1;
    
    it = 0;

    for i in range(28):
        for j in range(28):
            df_thresholded[col + str(it)] = gen[i][j];
            it += 1;

def threshold(row):
    global itt;
    col = "pixel";
    print(itt);
    itt += 1;

    for i in range(7):
        val = row[col + str(i)];

        if(val > 127): row[col + str(i)] = 1;
        else: row[col + str(i)] = 0;
    return row;

In [93]:
#train = train.apply(threshold, axis=1);



labels = (train['label']);
train = train.drop(columns=['label']);

scaler = MinMaxScaler((0, 1));
scaler.fit(train);

train = pd.DataFrame(scaler.transform(train));

train['label'] = labels
display(train)

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,label
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
41996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
41997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7
41998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
41999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9

In [94]:
#train.to_csv("save1.csv", index=False);
display(train);

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,label
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
41996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
41997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7
41998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6
41999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9

In [95]:
train, test = train_test_split(train, test_size=0.01);

train_f = train.drop(columns=['label']);
train_l = train['label'];

test_f = test.drop(columns=['label']);
test_l = test['label'];

In [96]:
model = MLPClassifier(solver='adam',alpha=1e-06, verbose=True, max_iter=10000, learning_rate="adaptive", tol=0.000001).fit(train_f, train_l);

Iteration 1, loss = 0.59672231
Iteration 2, loss = 0.27432368
Iteration 3, loss = 0.21765080
Iteration 4, loss = 0.18080142
Iteration 5, loss = 0.15451568
Iteration 6, loss = 0.13267991
Iteration 7, loss = 0.11707494
Iteration 8, loss = 0.10344365
Iteration 9, loss = 0.09253168
Iteration 10, loss = 0.08272576
Iteration 11, loss = 0.07354568
Iteration 12, loss = 0.06626337
Iteration 13, loss = 0.06015024
Iteration 14, loss = 0.05350217
Iteration 15, loss = 0.04807417
Iteration 16, loss = 0.04291513
Iteration 17, loss = 0.03849160
Iteration 18, loss = 0.03509051
Iteration 19, loss = 0.03169806
Iteration 20, loss = 0.02796073
Iteration 21, loss = 0.02531906
Iteration 22, loss = 0.02247715
Iteration 23, loss = 0.02014049
Iteration 24, loss = 0.01825100
Iteration 25, loss = 0.01583881
Iteration 26, loss = 0.01494452
Iteration 27, loss = 0.01327216
Iteration 28, loss = 0.01173510
Iteration 29, loss = 0.01063837
Iteration 30, loss = 0.00931703
Iteration 31, loss = 0.00827341
Iteration 32, loss = 0.00738262
Iteration 33, loss = 0.00683730
Iteration 34, loss = 0.00602058
Iteration 35, loss = 0.00546791
Iteration 36, loss = 0.00502852
Iteration 37, loss = 0.00440416
Iteration 38, loss = 0.00406037
Iteration 39, loss = 0.00361823
Iteration 40, loss = 0.00333421
Iteration 41, loss = 0.00339887
Iteration 42, loss = 0.00279793
Iteration 43, loss = 0.00247476
Iteration 44, loss = 0.00239008
Iteration 45, loss = 0.00222320
Iteration 46, loss = 0.00206399
Iteration 47, loss = 0.00180373
Iteration 48, loss = 0.00170578
Iteration 49, loss = 0.00145779
Iteration 50, loss = 0.00136439
Iteration 51, loss = 0.00119399
Iteration 52, loss = 0.00111194
Iteration 53, loss = 0.00099973
Iteration 54, loss = 0.00095660
Iteration 55, loss = 0.00084405
Iteration 56, loss = 0.00078081
Iteration 57, loss = 0.00077086
Iteration 58, loss = 0.00067470
Iteration 59, loss = 0.00062320
Iteration 60, loss = 0.00058157
Iteration 61, loss = 0.00053382
Iteration 62, loss = 0.00049089
Iteration 63, loss = 0.00044765
Iteration 64, loss = 0.00041744
Iteration 65, loss = 0.00039013
Iteration 66, loss = 0.00034638
Iteration 67, loss = 0.00032025
Iteration 68, loss = 0.00030216
Iteration 69, loss = 0.00027562
Iteration 70, loss = 0.00025554
Iteration 71, loss = 0.00024395
Iteration 72, loss = 0.00022664
Iteration 73, loss = 0.00020944
Iteration 74, loss = 0.00019295
Iteration 75, loss = 0.00017089
Iteration 76, loss = 0.00015849
Iteration 77, loss = 0.00014850
Iteration 78, loss = 0.00014193
Iteration 79, loss = 0.00012862
Iteration 80, loss = 0.00011806
Iteration 81, loss = 0.00011222
Iteration 82, loss = 0.00010086
Iteration 83, loss = 0.00009508
Iteration 84, loss = 0.00008933
Iteration 85, loss = 0.00008509
Iteration 86, loss = 0.00007670
Iteration 87, loss = 0.00007027
Iteration 88, loss = 0.00006549
Iteration 89, loss = 0.00006051
Iteration 90, loss = 0.00005678
Iteration 91, loss = 0.00005344
Iteration 92, loss = 0.00004966
Iteration 93, loss = 0.00004618
Iteration 94, loss = 0.00004317
Iteration 95, loss = 0.00004156
Iteration 96, loss = 0.00003830
Iteration 97, loss = 0.00003730
Iteration 98, loss = 0.00003445
Iteration 99, loss = 0.00003193
Iteration 100, loss = 0.00003002
Iteration 101, loss = 0.00002900
Iteration 102, loss = 0.00002810
Iteration 103, loss = 0.00002576
Iteration 104, loss = 0.00002452
Iteration 105, loss = 0.00002237
Iteration 106, loss = 0.00002149
Iteration 107, loss = 0.00002135
Iteration 108, loss = 0.00001934
Iteration 109, loss = 0.00001885
Iteration 110, loss = 0.00001781
Iteration 111, loss = 0.00001684
Iteration 112, loss = 0.00001608
Iteration 113, loss = 0.00001564
Iteration 114, loss = 0.00001565
Iteration 115, loss = 0.00001469
Iteration 116, loss = 0.00001381
Iteration 117, loss = 0.00001313
Iteration 118, loss = 0.00001292
Iteration 119, loss = 0.00001247
Iteration 120, loss = 0.00001209
Iteration 121, loss = 0.00001170
Training loss did not improve more than tol=0.000001 for 10 consecutive epochs. Stopping.

In [100]:
print(model.score(train_f, train_l));

1.0

In [98]:
real_data = pd.read_csv('test.csv');

scaler = MinMaxScaler((0, 1));
scaler.fit(real_data);

real_data = scaler.transform(real_data);
display(real_data);

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
pred_y = model.predict(train_f);

In [99]:
ans = pd.DataFrame(model.predict(real_data));
ans.index += 1;
ans.to_csv("ans.csv");